// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALS7KNIPiznldg420Ge8Z17926dR_GhOw',
    appId: '1:823445877942:android:a34207044226fde80de217',
    messagingSenderId: '823445877942',
    projectId: 'test-app-3fcaf',
    storageBucket: 'test-app-3fcaf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU8prf5T4cQuF5t0-vN7G4dRXvfbWbXsA',
    appId: '1:823445877942:ios:608699dac3b4ddd80de217',
    messagingSenderId: '823445877942',
    projectId: 'test-app-3fcaf',
    storageBucket: 'test-app-3fcaf.appspot.com',
    androidClientId: '823445877942-umkpu4v42dqq1oharrr9ec74pd5t5i11.apps.googleusercontent.com',
    iosClientId: '823445877942-3crt1tba8rv8dqv68gd0fv95qhf5mlh3.apps.googleusercontent.com',
    iosBundleId: 'com.example.briefTest',
  );
}
